---
- hosts: localhost
  connection: local
  tasks:
    - name: Deploy vultr servers
      vars:
        hostname: "{{  item.split('.')[0] | lower }}"
        hc_vault_server: "vault.whalewave.net:8200"
        hc_vault_token: "{{ vault_token }}"
        cloudflare_api_key: "{{ cloudflare_api_key }}"
        
        public_key_file_name: "./generated-host-keys/{{ item.split('.')[0] | lower }}/id_rsa.pub"
        private_key_file_name: "./generated-host-keys/{{ item.split('.')[0] | lower }}/id_rsa"

      include_tasks: create_vultr_server.yml
      loop: "{{ groups['vultr_servers'] }}"

- hosts: all
  gather_facts: no

  become: true

  pre_tasks:
    - name:
      wait_for_connection:
        delay: 5
        timeout: 600

  tasks:

    - name: Gather facts for first time
      setup:

    - name: Add motd
      template:
          src: templates/motd.j2
          dest: /etc/motd

  roles:
    - role: common-tools
    